// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiSdrRegqkVpOAeC9qgjj43e_1jO9PIN0',
    appId: '1:719377316001:web:a9d3a2db8fceaa2e21d8e0',
    messagingSenderId: '719377316001',
    projectId: 'testfirestore-fd7e2',
    authDomain: 'testfirestore-fd7e2.firebaseapp.com',
    databaseURL: 'https://testfirestore-fd7e2.firebaseio.com',
    storageBucket: 'testfirestore-fd7e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFixEmrkbKZKTfU3ebkAzQLj4Xu6Y9B-Q',
    appId: '1:719377316001:android:985ce6c58aaa72cd21d8e0',
    messagingSenderId: '719377316001',
    projectId: 'testfirestore-fd7e2',
    databaseURL: 'https://testfirestore-fd7e2.firebaseio.com',
    storageBucket: 'testfirestore-fd7e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC53TGkciQUmTO8HBZI04NcA7B5DUAC57E',
    appId: '1:719377316001:ios:bc643ddee5f0261021d8e0',
    messagingSenderId: '719377316001',
    projectId: 'testfirestore-fd7e2',
    databaseURL: 'https://testfirestore-fd7e2.firebaseio.com',
    storageBucket: 'testfirestore-fd7e2.appspot.com',
    androidClientId: '719377316001-0bdvnammejjch8ua3ldsnf6de7lncks9.apps.googleusercontent.com',
    iosClientId: '719377316001-5hritti5v3rkbptof9pg2efk4tialskn.apps.googleusercontent.com',
    iosBundleId: 'me.amryousef.apple.auth.firebaseAppleAuthExample',
  );
}
